#!/usr/bin/env python3
"""regen_rules.py — distill **Correction:**-flagged decisions into rules.md.

Reads framework + apparatus `DECISIONS.md`, filters to entries that carry an
explicit `**Correction:**` line, and writes `memory/brain/rules.md` — a
scannable rules-of-the-house digest. Source-of-truth remains the decision log;
this file is a derived view, regeneratable.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONSUMER = REPO.parent / "a_bgt_rsi"

FW_DECISIONS = REPO / "memory" / "DECISIONS.md"
AP_DECISIONS = CONSUMER / "DECISIONS.md"
RULES_MD = REPO / "memory" / "brain" / "rules.md"

DECISION_HEADER_RE = re.compile(
    r"^##\s+(?P<head>(?P<date>\d{4}-\d{2}-\d{2})|D-\d+)\s*[—–-]\s*(?P<title>[^\n]+)$",
    re.MULTILINE,
)
CORRECTION_LINE_RE = re.compile(r"^\*\*Correction:?\*\*\s*(?P<imperative>[^\n]+(?:\n(?!\*\*)[^\n]*)*)", re.MULTILINE)
SUPERSEDES_LINE_RE = re.compile(r"^\*\*Supersedes:?\*\*\s*(?P<value>[^\n]+)", re.MULTILINE)


def extract_corrections(path: Path, side: str) -> list[dict]:
    if not path.exists():
        return []
    text = path.read_text()
    headers = list(DECISION_HEADER_RE.finditer(text))
    out: list[dict] = []
    for i, m in enumerate(headers):
        start = m.end()
        end = headers[i + 1].start() if i + 1 < len(headers) else len(text)
        body = text[start:end].strip()
        corr = CORRECTION_LINE_RE.search(body)
        if not corr:
            continue
        sup = SUPERSEDES_LINE_RE.search(body)
        out.append({
            "side": side,
            "head": m.group("head"),
            "title": m.group("title").strip(),
            "date": m.group("date") or "",
            "imperative": corr.group("imperative").strip().rstrip(".") + ".",
            "supersedes": (sup.group("value").strip() if sup else "none"),
        })
    out.sort(key=lambda r: (r["date"] or r["head"], r["head"]))
    return out


def render(framework: list[dict], apparatus: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# Active rules")
    lines.append("")
    lines.append(
        "_Auto-generated by `scripts/regen_rules.py` from `memory/DECISIONS.md` "
        "(framework) and `a_bgt_rsi/DECISIONS.md` (apparatus). The decision log "
        "is canonical; this is a derived digest. Do not edit by hand — edit the "
        "source decision and re-run the script._"
    )
    lines.append("")
    lines.append(f"- Framework rules: {len(framework)}")
    lines.append(f"- Apparatus rules: {len(apparatus)}")
    lines.append("")

    def block(rules: list[dict], side_label: str, id_prefix: str) -> list[str]:
        block_lines = [f"## {side_label} rules", ""]
        if not rules:
            block_lines.append(f"_No `**Correction:**`-flagged decisions in {side_label.lower()} decision log._")
            block_lines.append("")
            return block_lines
        for i, r in enumerate(rules, 1):
            rid = f"{id_prefix}-{i:03d}"
            block_lines.append(f"### {rid} — {r['title']}")
            block_lines.append("")
            block_lines.append(f"- **Imperative:** {r['imperative']}")
            block_lines.append(f"- **Source decision:** `{r['head']}` ({r['date'] or 'undated'})")
            block_lines.append(f"- **Supersedes:** {r['supersedes']}")
            block_lines.append("")
        return block_lines

    lines.extend(block(framework, "Framework", "FR"))
    lines.extend(block(apparatus, "Apparatus", "AR"))
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    framework = extract_corrections(FW_DECISIONS, "framework")
    apparatus = extract_corrections(AP_DECISIONS, "apparatus")
    out = render(framework, apparatus)
    existing = RULES_MD.read_text() if RULES_MD.exists() else None
    if existing != out:
        RULES_MD.parent.mkdir(parents=True, exist_ok=True)
        RULES_MD.write_text(out)
        action = "wrote"
    else:
        action = "unchanged"
    print(f"{action} → {RULES_MD}")
    print(f"  framework rules: {len(framework)}  apparatus rules: {len(apparatus)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
